### ISSUE TITLE
Cloudflare R2 无法正常上传图片

### ISSUE THREAD

**Issue by kierankihn** [halo-dev/plugin-s3#88]
#### 问题描述

如图，使用 Cloudflare R2 S3 对象存储时无法上传图片，进度条卡住不动，开发者工具中显示 upload 一直是 pending 的状态

halo 中进度条卡在 100% 的位置，如果有多张图片的话只有第一张卡在 100%，其余为 0%

![](https://github.com/halo-dev/plugin-s3/assets/114803508/0f4a6f99-2cc7-4310-8499-3d28926cb015)

但是上传到本地存储则无此问题

#### 相关日志

```
halo    | 2023-10-18T17:23:46.406+08:00 ERROR 6 --- [dedElastic-1421] reactor.core.scheduler.Schedulers        : Scheduler worker in group main failed with an uncaught exception
halo    |
halo    |
halo    | java.lang.LinkageError: loader constraint violation: when resolving method 'reactor.core.publisher.Flux reactor.core.publisher.Mono.thenMany(org.reactivestreams.Publisher)' the class loader org.pf4j.PluginClassLoader @61d07fc8 of the current class, run/halo/s3os/S3OsAttachmentHandler, and the class loader org.springframework.boot.loader.LaunchedURLClassLoader @61bbe9ba for the method's defining class, reactor/core/publisher/Mono, have different Class objects for the type org/reactivestreams/Publisher used in the signature (run.halo.s3os.S3OsAttachmentHandler is in unnamed module of loader org.pf4j.PluginClassLoader @61d07fc8, parent loader org.springframework.boot.loader.LaunchedURLClassLoader @61bbe9ba; reactor.core.publisher.Mono is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @61bbe9ba, parent loader 'app')
halo    |       at run.halo.s3os.S3OsAttachmentHandler.lambda$upload$28(S3OsAttachmentHandler.java:298) ~[na:na]
halo    |       at reactor.core.publisher.MonoUsing.subscribe(MonoUsing.java:85) ~[reactor-core-3.5.10.jar:3.5.10]
halo    |       at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[reactor-core-3.5.10.jar:3.5.10]
halo    |       at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.5.10.jar:3.5.10]
halo    |       at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.10.jar:3.5.10]
halo    |       at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.10.jar:3.5.10]
halo    |       at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
halo    |       at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
halo    |       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
halo    |       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
halo    |       at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo    |
halo    |
```

#### 系统版本

Halo 2.10，S3 插件 1.5.0

**Comment by longjuan** [comment]
1.5.0已经解决了这个问题，可以尝试重启halo容器。

**Comment by kierankihn** [comment]
重启容器之后问题已经解决
